### ISSUE TITLE
[상품] 이미지가 등록된 상품 수정시 상품 이미지 신규 등록하지 않을 경우 기존 이미지 누락됨

### ISSUE THREAD

**Issue by KimYeonChan34** [ssg-java3-240304/shop-Animal-Playground#27]
## ✒Description
[실행환경]
* 브랜치: release
* 커밋: [fb18ee2](https://github.com/Parkminem/shop-Animal-Playground/commit/fb18ee23f7b8166f00d3492d0d901a95f6531e37)

[이미지]
* 기존 이미지가 등록된 상품의 수정화면
<img width="1481" alt="스크린샷 2024-06-27 오전 10 34 11" src="https://github.com/ssg-java3-240304/shop-Animal-Playground/assets/93385959/2df7fdfe-f738-44a9-b19e-3aaa479229dd">
* 신규 이미지 등록하지 않고 수정하기 버튼 클릭시
<img width="1472" alt="스크린샷 2024-06-27 오전 10 34 45" src="https://github.com/ssg-java3-240304/shop-Animal-Playground/assets/93385959/2c6576cf-cb8e-414c-b4a1-49e92563bc7e">

## ⚒ Reproduction
1. 상품 이미지가 등록된 상품의 수정화면 진입
2. 상품 이미지를 신규 등록하지 않고 [수정] 버튼 클릭
3. 상품 상세화면 진입시 기존 등록된 이미지 누락되어 노출됨

**Comment by Parkminem** [comment]
현재 데이터베이스에 존재하는 이미지를 가져와서 if / else 처리하여 이미지가 존재하면 현재 이미지가 넘어가도록 수정
